package example.domain

/**
  * Entity representing User object.
  * @param id unique identifier of the user.
  * @param username the name of the user.
  * @param address the address of the user. Optional.
  * @param email the user email address.
  */
case class User(id: Long, username: String, address: Option[String], email: String)

/**
  * Entity representing new User object. Id will be generated by the system.
  * @param username the name of the user.
  * @param address the address of the user. Optional.
  * @param email the user email address.
  */
case class NewUser(username: String, address: Option[String], email: String)
